import{a as S,i as f,S as M}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();async function u(t,r){const e="https://pixabay.com"+"/api/",o={key:"43044638-81b288208bd41d7f3c4a2027f",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,pageSize:15};return(await S.get(e,{params:o})).data}function g(t){return t.length===0&&(d(),f.error({message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})),t.map(({webformatURL:l,largeImageURL:a,tags:e,likes:o,views:n,comments:b,downloads:E})=>`<li class="gallery-item">
    <a class="gallery-link" href="${a}">
    <img class="gallery-image" src="${l}" alt="${e}" />
    </a>
    <div class="content-image">
    <p class="content-item">Likes<span class="info-item">${o}</span></p>
    <p class="content-item">Views<span class="info-item">${n}</span></p>
    <p class="content-item">Comments<span class="info-item">${b}</span></p>
    <p class="content-item">Downloads<span class="info-item">${E}</span></p>
    </div
    </li>`).join("")}const s={galleryElement:document.querySelector(".gallery"),form:document.querySelector(".form"),loader:document.querySelector(".conteiner-loader"),btnLoadMore:document.querySelector(".loadMore")};let c,i=1,p=0;const v=15;function h(){s.loader.classList.remove("is-hidden")}function d(){s.loader.classList.add("is-hidden")}function P(){s.btnLoadMore.classList.remove("is-hidden")}function y(){s.btnLoadMore.classList.add("is-hidden")}s.form.addEventListener("submit",w);s.btnLoadMore.addEventListener("click",q);async function w(t){if(t.preventDefault(),y(),i=1,c=t.target.elements.query.value.trim(),s.galleryElement.innerHTML="",!c){d(),f.info({message:" Please fill in the field for search",position:"topRight"}),s.galleryElement.innerHTML="";return}try{h();const r=await u(c,i);p=Math.ceil(r.totalHits/v),s.galleryElement.insertAdjacentHTML("beforeend",g(r.hits)),m.refresh()}catch(r){console.log(r)}d(),L(),t.target.reset()}async function q(){try{i+=1;const t=await u(c,i);s.galleryElement.insertAdjacentHTML("beforeend",g(t.hits)),m.refresh()}catch(t){console.log(t)}F(),L(),d()}function L(){i>=p?(y(),f.info({color:"yellow",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):P()}function F(){const t=s.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({top:t*2,behavior:"smooth"})}const m=new M(".gallery a",{captionsData:"alt",captionDelay:250});m.refresh();
//# sourceMappingURL=commonHelpers.js.map
