import{a as M,i as m,S as v}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();async function u(o,r){const e="https://pixabay.com"+"/api/",t={key:"43044638-81b288208bd41d7f3c4a2027f",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,pre_page:15};return(await M.get(e,{params:t})).data}function p(o){return o.map(({webformatURL:l,largeImageURL:a,tags:e,likes:t,views:s,comments:b,downloads:E})=>`<li class="gallery-item">
    <a class="gallery-link" href="${a}">
    <img class="gallery-image" src="${l}" alt="${e}" />
    </a>
    <div class="content-image">
    <p class="content-item">Likes<span class="info-item">${t}</span></p>
    <p class="content-item">Views<span class="info-item">${s}</span></p>
    <p class="content-item">Comments<span class="info-item">${b}</span></p>
    <p class="content-item">Downloads<span class="info-item">${E}</span></p>
    </div
    </li>`).join("")}const n={galleryElement:document.querySelector(".gallery"),form:document.querySelector(".form"),loader:document.querySelector(".conteiner-loader"),btnLoadMore:document.querySelector(".loadMore")};let c,i=1,g=0;const w=15;n.form.addEventListener("submit",S);n.btnLoadMore.addEventListener("click",P);async function S(o){if(o.preventDefault(),y(),i=1,c=o.target.elements.query.value.trim(),n.galleryElement.innerHTML="",!c){f(),m.info({message:" Please fill in the field for search",position:"topRight"}),n.galleryElement.innerHTML="";return}try{h();const r=await u(c,i);g=Math.ceil(r.totalHits/w),n.galleryElement.insertAdjacentHTML("beforeend",p(r.hits)),d.refresh()}catch(r){console.log(r)}f(),L(),o.target.reset()}async function P(){try{i+=1;const o=await u(c,i);n.galleryElement.insertAdjacentHTML("beforeend",p(o.hits)),d.refresh()}catch(o){console.log(o)}O(),L()}function h(){n.loader.classList.remove("is-hidden")}function f(){n.loader.classList.add("is-hidden")}function q(){n.btnLoadMore.classList.remove("is-hidden")}function y(){n.btnLoadMore.classList.add("is-hidden")}function L(){i>g?(y(),m.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q()}function O(){const o=n.galleryElement.firstChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const d=new v(".gallery a",{captionsData:"alt",captionDelay:250});d.refresh();
//# sourceMappingURL=commonHelpers.js.map
